# Site settings
title: GameRunners News
email: news@gamerunners.gg
description: League of Legends community driven news articles. Read about pro level character analysis, theory crafting, past tournament breakdowns, and more!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://news.gamerunners.gg" # the base hostname & protocol for your site
twitter_username: GameRunnersGG

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap