# Site settings
title: GameRunners
email: news@gamerunners.gg
description: "League of Legends coaching community driven news articles. Read about pro LoL interviews, pro champion analysis, theory crafting, tournament breakdowns, and more!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://news.gamerunners.gg" # the base hostname & protocol for your site
twitter_username: GameRunnersGG

# Build settings
markdown: kramdown

# Outputting
permalink: :categories/:title

gems:
  - jekyll-sitemap